// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tjlprkreldxveziivpas.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRqbHBya3JlbGR4dmV6aWl2cGFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4Njg1NTQsImV4cCI6MjA3MjQ0NDU1NH0.pgN8kOPYVBreMYvyb0doqsuOG8e962MPXTQvkoyzzOE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});